config/routes.rb
Rails.application.routes.draw do
  devise_for :shop,controllers: {
  registrations: "shop/registrations",
  sessions: 'shop/sessions',
  passwords: 'shop/passwords'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :customer,controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}
 resources :maps
  scope module: :public do
    root "homes#top"
    get '/' => "homes#top"
    get '/about' => "homes#about"
    get '/customers/mypage' => "customers#show"
    get '/customers/mypage/edit' => "customers#edit"  
    patch  '/customers/mypage' => "customers#update"
    get "search" => "searches#index"
    get 'unsubscribe/:id' => 'homes#unsubscribe', as: 'confirm_unsubscribe'
    patch ':id/withdraw' => 'homes#withdraw', as: 'withdraw_customer'
    put 'withdraw/:name' => 'customers#withdraw'
    resources :stores do
     resource :bookmarks, only: [:create, :destroy]
    end
    resources :store_photos
    resource :customers
    resources :reviews
    resources :blogs
    resources :maps
  end
    namespace :admin do
      root "homes#top" 
      get "search" => "searches#search"
      get 'unsubscribe/customer/:id' => 'customers#unsubscribe'
      get 'unsubscribe/shop/:id' => 'shops#unsubscribe'
      patch 'customer/:id/withdraw' => 'customers#withdraw'
      patch 'shop/:id/withdraw' => 'shops#withdraw'
      resources :applications
      resources :shops
      resources :customers
      resources :reviews
      resources :blogs
      resources :shop_photos
      resources :nearest_station
      resources :maps
    end
    namespace :shop do
      root "homes#top" 
      get '/mypage' => "mypages#show"
      get '/mypage/edit' => "mypages#edit"
      patch '/mypage/edit' => "mypages#update"
      get 'unsubscribe/:id' => 'homes#unsubscribe', as: 'confirm_unsubscribe'
      patch ':id/withdraw' => 'homes#withdraw', as: 'withdraw_shop'
      put 'withdraw/:name' => 'shops#withdraw'
   
      resources :blogs
      resources :reviews
      resources :mypages
      resources :homes
      resources :shop_photos
      resources :maps
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
      has_one_attached :image
      belongs_to :shop
      validates :title, presence: true
      validates :introduction, presence: true
end

app/models/book_mark.rb
class BookMark < ApplicationRecord
    belongs_to :customer
    belongs_to :shop
    validates :customer_id, uniqueness: { scope: :shop_id }
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :shop
  validates :customer_id, uniqueness: { scope: :shop_id }
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :reviews
  has_many :bookmarks  ,dependent: :destroy
  # フォローをした、されたの関係
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

# 一覧画面で使う
has_many :followings, through: :relationships, source: :followed
has_many :followers, through: :reverse_of_relationships, source: :follower
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where("nickname LIKE?","#{word}")
    elsif search == "forward_match"
      @customer = Customer.where("nickname LIKE?","#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("nickname LIKE?","%#{word}")
    elsif search == "partial_match"
      @customer = Customer.where("nickname LIKE?","%#{word}%")
    else
      @customer = Customer.all
    end
  end
end

app/models/map.rb
class Map < ApplicationRecord
    geocoded_by :address
    after_validation :geocode
end

app/models/map_query.rb
class MapQuery < ApplicationRecord
  def initialize(address)
    @shop_param = address
  end
  def uri
    # フォームから飛んできた住所をエスケープして変数に格納
    address = URI.encode_www_form({address: @shop_param})
    # Geocoding APIを叩く
    URI.parse("https://maps.googleapis.com/maps/api/geocode/json?#{address}&key=#{ENV["GOOGLE_MAP_API_KEY"]}")
  end

  def result
    # 返ってきたJSONをパースしてapi_response という変数に格納
    api_response = Net::HTTP.get_response(uri)
    response_body = JSON.parse(api_response.body)
    response_body["results"][0]["geometry"]["location"]
  end
end

app/models/nearest_station.rb
class NearestStation < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
      has_one_attached :image
    belongs_to :customer
    belongs_to :shop
    validates :title, presence: true
    validates :introduction, presence: true
    validates :shop_id, presence: true
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :blogs
  has_many :bookmarks, dependent: :destroy
  has_many :shop_photos
  has_many :reviews
  
  validates :name, presence: true
  
  def bookmarked_by?(customer)
    bookmarks.where(customer_id: customer).exists?
  end
  
  def self.search(keyword)
    unless keyword.blank?
      Shop.where(['name LIKE ?', "%#{keyword}%"])
    else
      Shop.all
    end
  end
   def self.looks(search, word)
    if search == "perfect_match"
      @shop = Shop.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @shop = Shop.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @shop = Shop.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @shop = Shop.where("name LIKE?","%#{word}%")
    else
      @shop = Shop.all
    end
  end
  
  def self.address_search(address_keyword)
    unless address_keyword.blank?
      Shop.where(['address LIKE ?', "%#{address_keyword}%"])
    else
      Shop.all
    end
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/shop_photo.rb
class ShopPhoto < ApplicationRecord
    has_one_attached :image
    belongs_to :shop
    validates :image, presence: true
    validates :introduction, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :name, :address, :introduction, :opening_hours, :longitude, :latitude])
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    def _google_map
        @maps = Map.all
        @map = Map.new
    end
    
    def create
        map = Map.new(map_params)
        if map.save
            if current_shop.present?
            redirect_to shop_root_path
            else
            redirect_to  root_path
             end
        else
             if current_shop.present?
            redirect_to shop_root_path
            else
            redirect_to root_path
             end
        end
    end

    def destroy
        map = Map.find(params[:id])
        map.destroy
        redirect_to action: :index
    end

    private
    def map_params
    params.require(:map).permit(:address, :latitude, :longitude)
    end
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/shop/blogs_helper.rb
module Shop::BlogsHelper
end

app/helpers/shop/homes_helper.rb
module Shop::HomesHelper
end

app/helpers/shop/mypages_helper.rb
module Shop::MypagesHelper
end

app/helpers/shop/reviews_helper.rb
module Shop::ReviewsHelper
end

app/views/maps/_google_map.html.erb
<h2>Google map</h2>

<input id="address" type="textbox" value="">
<input type="button" value="地図を検索" onclick="codeAddress()">
<div id="display">緯度経度が表示されるよ！</div>

<div id='map'></div>

<style>
    #map {
        height: 400px;
        width: 100%;
    }
</style>

<script>
    let map;

    // mapの表示関数 
    // initMap(35.6010006,139.7218381)
    function initMap(lat, lng) {
        <% mapNotFlg = true %>
        <% Shop.all.each do |shop| %>
            <% if shop.latitude.present? && shop.longitude.present? %>
                <% if mapNotFlg %>
                    // mapの初期位置, 縮尺を定義
                    map = new google.maps.Map(document.getElementById('map'), {
                        center: {
                            lat: (typeof lat === 'number') ? lat : <%= shop.latitude %>,
                            lng: (typeof lng === 'number') ? lng : <%= shop.longitude %>,
                            // lat: 35.6010006,
                            // lng: 139.7218381
                        },
                        zoom: 15,
                    });
                    new google.maps.Marker({
                        position:{lat: <%= shop.latitude %>, lng: <%= shop.longitude %>},
                        map: map
                    });
 
                    <% mapNotFlg = false %>
                <% else %>
                    new google.maps.Marker({
                        position:{lat: <%= shop.latitude %>, lng: <%= shop.longitude %>},
                        map: map
                    });

                <% end %>
            <% end %>
        <% end %>
    }
        function codeAddress() {

        let inputAddress = document.getElementById('address').value;
        var geocoder = new google.maps.Geocoder();
        geocoder.geocode( { 'address':inputAddress}, function(results, status) {
          // ジオコーディングが成功した場合
          if (status == google.maps.GeocoderStatus.OK) {
            console.log(status)
            map = new google.maps.Map(document.getElementById('map'), {
                        center: {
                            lat: results[0].geometry.location.lat(),
                            lng: results[0].geometry.location.lng()
                        },
                        zoom: 15,
                    });
            <% Shop.all.each do |shop| %>
                <% if shop.latitude.present? && shop.longitude.present? %>
                    <% if mapNotFlg %>
                        // mapの初期位置, 縮尺を定義
                        new google.maps.Marker({
                            position:{lat: <%= shop.latitude %>, lng: <%= shop.longitude %>},
                            map: map
                        });
                        <% mapNotFlg = false %>
                    <% else %>
                        new google.maps.Marker({
                            position:{lat: <%= shop.latitude %>, lng: <%= shop.longitude %>},
                            map: map
                        });
                    <% end %>
                <% end %>
            <% end %>
            
           
          // ジオコーディングが成功しなかった場合
          }   
        });
    }
</script>



<script
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap"  
    async defer>
</script>

<!--<h3>場所投稿フォーム</h3>-->
<!--<#%= form_with model: map, url: maps_path, method: :post do |f| %>-->

<!--    <p>-->
<!--    <%#= f.label :address %>-->
<!--    <%#= f.text_field :address, size: "50x1" %>-->
<!--    </p>-->

<!--    <%#= f.submit "送信", id: "button", onclick: "return codeAddress()" %>-->
<!--<%# end %>-->

<!--<h3>場所一覧</h3>-->
<!--<%# maps.each do |t| %>-->
<!--    <p>住所 : <%#= t.address %></p>-->
<!--    <p>緯度 : <%#= t.latitude %></p>-->
<!--    <p>経度 : <%#= t.longitude %></p>-->
<!--    <p><%#= link_to "削除する", map_path(t.id), method: :delete %></p>-->
<!--    <hr>-->
<!--<%# #end %>-->