config/routes.rb
Rails.application.routes.draw do
  devise_for :shop,controllers: {
  registrations: "shop/registrations",
  sessions: 'shop/sessions',
  passwords: 'shop/passwords'
}
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  devise_for :customer,controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}
 resources :maps
  scope module: :public do
    root "homes#top"
    get '/' => "homes#top"
    get '/about' => "homes#about"
    get '/customers/mypage' => "customers#show"
    get '/customers/mypage/edit' => "customers#edit"  
    patch  '/customers/mypage' => "customers#update"
    get "search" => "searches#index"
    get 'unsubscribe/:id' => 'homes#unsubscribe', as: 'confirm_unsubscribe'
    patch ':id/withdraw' => 'homes#withdraw', as: 'withdraw_customer'
    put 'withdraw/:name' => 'customers#withdraw'
    resources :stores do
     resource :bookmarks, only: [:create, :destroy]
    end
    resources :store_photos
    resource :customers
    resources :reviews
    resources :blogs
    resources :maps
  end
    namespace :admin do
      root "homes#top" 
      get "search" => "searches#search"
      get 'unsubscribe/customer/:id' => 'customers#unsubscribe'
      get 'unsubscribe/shop/:id' => 'shops#unsubscribe'
      patch 'customer/:id/withdraw' => 'customers#withdraw'
      patch 'shop/:id/withdraw' => 'shops#withdraw'
      resources :applications
      resources :shops
      resources :customers
      resources :reviews
      resources :blogs
      resources :shop_photos
      resources :nearest_station
      resources :maps
    end
    namespace :shop do
      root "homes#top" 
      get '/mypage' => "mypages#show"
      get '/mypage/edit' => "mypages#edit"
      patch '/mypage/edit' => "mypages#update"
      get 'unsubscribe/:id' => 'homes#unsubscribe', as: 'confirm_unsubscribe'
      patch ':id/withdraw' => 'homes#withdraw', as: 'withdraw_shop'
      put 'withdraw/:name' => 'shops#withdraw'
   
      resources :blogs
      resources :reviews
      resources :mypages
      resources :homes
      resources :shop_photos
      resources :maps
    end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :reviews
  has_many :bookmarks  ,dependent: :destroy
  # フォローをした、されたの関係
has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

# 一覧画面で使う
has_many :followings, through: :relationships, source: :followed
has_many :followers, through: :reverse_of_relationships, source: :follower
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where("nickname LIKE?","#{word}")
    elsif search == "forward_match"
      @customer = Customer.where("nickname LIKE?","#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("nickname LIKE?","%#{word}")
    elsif search == "partial_match"
      @customer = Customer.where("nickname LIKE?","%#{word}%")
    else
      @customer = Customer.all
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @customer = Customer.find(params[:id])
    @reviews = Review.where(customer_id: @customer.id).page(params[:review_page]).per(5)
    @bookmarks = Bookmark.where(customer_id: @customer.id).page(params[:bookmark_page]).per(5)
  end
  def unsubscribe
    @customer = Customer.find(params[:id])
  end
   def withdraw
    @customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
     redirect_to admin_root_path
 end
  def update
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/show.html.erb
<h1 class="h1-text">会員情報</h1>
<table class = "table">
 <tbody>
  <tr>
   <th><%="ニックネーム"%></th>
   <td><%= @customer.nickname%></td>
  </tr>
  <tr>
   <th><%="email"%></th>
   <td><%= @customer.email%></td>
  </tr>
 </tbody>
</table>
<h3>レビュー一覧</h3>
<table class = "table">
 <thead>
  <tr>
   <th><%="レビュー店舗名"%></th>      
   <th><%="タイトル"%></th>
   <th><%="作成日時"%></th>
   <th><%= ""%></th>
  </tr>     
 </thead>   
 <tbody>
<% @reviews.each do |review|%>     
  <tr>
   <td><%= review.shop.name%></td>
   <td><%= review.title%></td>
   <td><%=review.created_at.strftime("%Y/%m/%d")%></td>
   <td><%= link_to"詳細ページへ", admin_review_path(review.id) %></td>
  </tr>
<% end %>
 </tbody>
</table>
<%= paginate @reviews, param_name: 'review_page' %>
<h3>登録店舗一覧</h3>
<table class = "table">
 <thead>
 <tr>
  <th><%= "店舗名"%></th>
  <th><%= "住所"%></th>
  <th><%= ""%></th>
 </tr>
 </thead>
 <tbody>
     <% @bookmarks.each do |bookmark|%>
  <tr>
   <td><%= bookmark.shop.name %></td>  
   <td><%= bookmark.shop.address %></td>
   <td><%= link_to"詳細ページへ", admin_shop_path(bookmark.id) %></td>
  </tr> 
     <% end %>

 </tbody>
</table>
     <%= paginate @bookmarks, param_name: 'bookmark_page'%>
<% if @customer.is_deleted == false %>     
<%= link_to "このアカウントを削除する", "/admin/unsubscribe/customer/#{@customer.id}",class: "btn btn-danger" %>
<% else %>
<h3 class = "h3-text">このアカウントは削除されています</h3>
<% end %>

app/views/admin/customers/unsubscribe.html.erb
<div>
  <h2>本当に退会しますか？</h2>
  <div>
    <p>退会する場合は、『退会する』をクリックしてください。</p>
  </div>
  <div>
    <%= link_to '退会しない', admin_root_path,class: "btn btn-primary"  %>
    <%= link_to "退会する", "/admin/customer/#{@customer.id}/withdraw",  method: :patch,class: "btn btn-danger" %>
  </div>
</div>